name: TFLint

on:
  - pull_request
  - push

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set-up TFLint
        uses: terraform-linters/setup-tflint@1cf010d3c7aef302051ccdb68c14c5dc2efa34ef # v6.3.1

      - name: Run TFLint
        run: tflint --recursive --format=compact
